# buildZxScript { pname, version, src, entrypoint, ... }
#
# Single-step packager for zx (google/zx) TypeScript scripts.
#
# Three usage tiers:
#
#   Tier 1 — zero-config (just zx):
#     buildZxScript { pname = "my-tool"; src = ./.; }
#
#   Tier 2 — extra npm deps (zero-transitive-dep packages):
#     buildZxScript {
#       pname = "my-tool"; src = ./.;
#       extraDeps = {
#         "chalk@5.4.1" = pkgs.fetchurl {
#           url = "https://registry.npmjs.org/chalk/-/chalk-5.4.1.tgz";
#           hash = "sha512-...";  # nix-prefetch-url <url>
#         };
#       };
#     }
#
#   Tier 3 — full override (deps with transitive trees):
#     buildZxScript {
#       pname = "my-tool"; src = ./.;  # src must contain bun.lock
#       bunNix = ./bun.nix;            # generated by bun2nix
#     }
#
#   Tier 4 — file-based deps (///!dep directives in the script):
#     buildZxScriptFromFile {
#       pname = "my-tool";
#       script = ./my-tool.ts;  # deps declared inline
#     }
#
# The wrapper unsets LD_LIBRARY_PATH to prevent devshell library leaks
# (see amarbel-llc/bun#4).
{ pkgs, lib, bun, fetchBunDeps }:

let
  # -- Helpers --

  # Map a .ts/.tsx/.mts/.cts basename to .js
  tsToJs =
    name:
    lib.replaceStrings
      [ ".ts" ".tsx" ".mts" ".cts" ]
      [ ".js" ".js" ".js" ".js" ]
      (builtins.baseNameOf name);

  # Parse "name@version" into { name, version }.
  parseDepKey =
    key:
    let
      # Split on last @ (handles scoped packages like @scope/pkg@1.0.0)
      parts = lib.splitString "@" key;
      len = builtins.length parts;
      # For "@scope/pkg@1.0.0" → ["" "scope/pkg" "1.0.0"]
      # For "pkg@1.0.0" → ["pkg" "1.0.0"]
      name =
        if len == 3 then
          "@${builtins.elemAt parts 1}"
        else
          builtins.elemAt parts 0;
      version = builtins.elemAt parts (len - 1);
    in
    { inherit name version; };

  # Construct the npm registry tarball URL for a "name@version" key.
  mkTarballUrl =
    key:
    let
      parsed = parseDepKey key;
      bareName =
        if lib.hasPrefix "@" parsed.name then
          builtins.elemAt (lib.splitString "/" parsed.name) 1
        else
          parsed.name;
    in
    "https://registry.npmjs.org/${parsed.name}/-/${bareName}-${parsed.version}.tgz";

  # -- Vendored zx dependency --
  # Bump: update zxVersion and zxHash together.
  zxVersion = "8.8.5";
  zxHash = "sha512-SNgDF5L0gfN7FwVOdEFguY3orU5AkfFZm9B5YSHog/UDHv+lvmd82ZAsOenOkQixigwH2+yyH198AwNdKhj+RA==";
  zxDep = {
    "zx@${zxVersion}" = pkgs.fetchurl {
      url = mkTarballUrl "zx@${zxVersion}";
      hash = zxHash;
    };
  };

  # -- Eval-time directive parsers (for buildZxScriptFromFile) --

  # Extract ///!dep directives from script content.
  # Returns a list of { key, hash } attrsets.
  # Throws at eval time if any directive is missing its SRI hash.
  parseDepLines =
    scriptPath: content:
    let
      lines = builtins.filter builtins.isString (builtins.split "\n" content);
      parseLine =
        line:
        let
          depWithHash = builtins.match "^///!dep[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+).*" line;
          depWithoutHash = builtins.match "^///!dep[[:space:]]+([^[:space:]]+)[[:space:]]*$" line;
        in
        if depWithHash != null then
          {
            key = builtins.elemAt depWithHash 0;
            hash = builtins.elemAt depWithHash 1;
          }
        else if depWithoutHash != null then
          builtins.throw ''
            buildZxScriptFromFile: ///!dep ${builtins.elemAt depWithoutHash 0} has no SRI hash.

            Run: bun scripts/update-zx-deps.ts ${builtins.toString scriptPath}
          ''
        else
          null;
    in
    builtins.filter (x: x != null) (builtins.map parseLine lines);

  # Generate synthetic package.json content from a dep attrset.
  mkPackageJson =
    pname: allDeps:
    let
      deps = lib.mapAttrs' (
        key: _:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name parsed.version
      ) allDeps;
    in
    builtins.toJSON {
      name = pname;
      dependencies = deps;
    };

  # Generate synthetic bun.lock content from a dep attrset.
  # Each dep becomes a lockfile package tuple:
  #   [resolved_spec, "", {}, integrity_hash]
  mkBunLock =
    pname: allDeps:
    let
      deps = lib.mapAttrs' (
        key: _:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name parsed.version
      ) allDeps;

      packages = lib.mapAttrs' (
        key: dep:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name [
          key
          ""
          { }
          dep.outputHash
        ]
      ) allDeps;
    in
    builtins.toJSON {
      lockfileVersion = 1;
      workspaces = {
        "" = {
          name = pname;
          dependencies = deps;
        };
      };
      inherit packages;
    };

  # Create a wrapper script for a single binary.
  mkWrapper =
    {
      name,
      bundle,
      jsFile,
      runtimeInputs ? [ ],
      runtimeEnv ? { },
    }:
    let
      envExports = lib.concatStringsSep "\n" (
        lib.mapAttrsToList (k: v: "export ${k}=${lib.escapeShellArg v}") runtimeEnv
      );
      pathSetup = lib.optionalString (runtimeInputs != [ ]) ''
        export PATH="${lib.makeBinPath runtimeInputs}:$PATH"
      '';
    in
    pkgs.writeShellScriptBin name ''
      ${envExports}
      ${pathSetup}
      unset LD_LIBRARY_PATH
      exec ${bun}/bin/bun ${bundle}/${jsFile} "$@"
    '';

  buildZxScript =
    {
      pname,
      version ? "0.0.0",
      src,
      entrypoint ? "index.ts",
      bunNix ? null,
      bunBuildFlags ? [ ],
      runtimeInputs ? [ ],
      runtimeEnv ? { },
      extraDeps ? { },
      bunfigPath ? null,
      npmrcPath ? null,
      overrides ? { },
      _skipBuiltinZx ? false,
      ...
    }:
    let
      # Tier 3: full override via bunNix
      useBunNix = bunNix != null;

      # Tiers 1 & 2: merge vendored zx with extraDeps
      # When _skipBuiltinZx is true (used by buildZxScriptFromFile), the
      # caller provides the zx dep via extraDeps from the script directives.
      allDeps = (if _skipBuiltinZx then { } else zxDep) // extraDeps;

      # -- Cache --
      # Tier 3: use fetchBunDeps (same as buildBunBinary)
      # Tiers 1&2: symlinkJoin of fetchurl tarballs
      cache =
        fetchBunDeps {
          bunNix =
            if useBunNix then
              bunNix
            else
              # Programmatic bunNix: ignore injected fetchurl, return
              # pre-fetched tarballs directly.
              { ... }:
              allDeps;
          inherit bunfigPath npmrcPath overrides;
        };

      # -- Synthetic files (tiers 1 & 2 only) --
      syntheticPackageJson = pkgs.writeText "${pname}-package.json" (mkPackageJson pname allDeps);
      syntheticBunLock = pkgs.writeText "${pname}-bun.lock" (mkBunLock pname allDeps);

      # -- Bundle derivation --
      bundle = pkgs.stdenvNoCC.mkDerivation {
        pname = "${pname}-bundle";
        inherit version src;

        nativeBuildInputs = [ bun ];

        buildPhase =
          ''
            runHook preBuild

            export BUN_INSTALL_CACHE_DIR=$(mktemp -d)
          ''
          + ''
            cp -r ${cache}/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"
          ''
          + (
            if useBunNix then
              # Tier 3: src contains bun.lock
              ''
                bun install --frozen-lockfile --linker=isolated
              ''
            else
              # Tiers 1&2: inject synthetic package.json + bun.lock
              ''
                cp ${syntheticPackageJson} package.json
                cp ${syntheticBunLock} bun.lock
                bun install --frozen-lockfile --linker=isolated
              ''
          )
          + ''
            mkdir -p $out
            bun build ${lib.escapeShellArg entrypoint} \
              --target=bun \
              --format=esm \
              --outdir=$out \
              ${lib.escapeShellArgs bunBuildFlags}

            runHook postBuild
          '';

        dontInstall = true;
        dontFixup = true;
      };
    in
    mkWrapper {
      name = pname;
      inherit bundle runtimeInputs runtimeEnv;
      jsFile = tsToJs entrypoint;
    };

  # Tier 4: file-based deps — deps declared inline via ///!dep directives.
  #
  # Usage:
  #   buildZxScriptFromFile {
  #     pname = "my-tool";
  #     script = ./my-tool.ts;
  #   }
  #
  # The script must contain ///!dep directives with SRI hashes:
  #   ///!dep zx@8.8.5 sha512-SNgDF5L0gfN7FwVOd...
  #   ///!dep chalk@5.4.1 sha512-zgVZuo2WcZgfUEm...
  #
  # Use `bun scripts/update-zx-deps.ts <script>` to resolve hashes.
  buildZxScriptFromFile =
    {
      pname,
      version ? "0.0.0",
      script,
      bunBuildFlags ? [ ],
      runtimeInputs ? [ ],
      runtimeEnv ? { },
      ...
    }:
    let
      content = builtins.readFile script;
      deps = parseDepLines script content;

      extraDeps = builtins.listToAttrs (
        builtins.map (dep: {
          name = dep.key;
          value = pkgs.fetchurl {
            url = mkTarballUrl dep.key;
            hash = dep.hash;
          };
        }) deps
      );

      entrypoint = builtins.baseNameOf (builtins.toString script);

      srcDir = pkgs.runCommandLocal "${pname}-src" { } ''
        mkdir -p $out
        cp ${script} $out/${entrypoint}
      '';
    in
    buildZxScript {
      inherit
        pname
        version
        bunBuildFlags
        runtimeInputs
        runtimeEnv
        extraDeps
        entrypoint
        ;
      src = srcDir;
      _skipBuiltinZx = true;
    };

in
{
  inherit buildZxScript buildZxScriptFromFile;
}
