/**
  Build a Bun TypeScript/JavaScript project into a self-contained binary
  (shell wrapper + pre-built ESM bundle).

  `buildBunBinary` produces `$out/bin/$pname` from a single entrypoint.
  `buildBunBinaries` produces `$out/bin/{name,...}` from multiple entrypoints
  sharing one bundle derivation (one `bun install` + one `bun build`).

  Uses ESM format rather than `--bytecode` to support top-level await.
  The `bun` argument is overridable for callers that need a trimmed runtime.

  # Inputs

  `pname`
  : Package name; becomes the binary name for `buildBunBinary`.

  `version`
  : Package version string.

  `src`
  : Source tree containing the TypeScript/JavaScript project.

  `entrypoint` (optional, default `"index.ts"`)
  : Source-relative path to the entry file. (`buildBunBinary` only.)

  `entrypoints` (for `buildBunBinaries`)
  : Attrset mapping binary names to source-relative entry paths,
    e.g. `{ "my-cli" = "src/cli.ts"; "my-daemon" = "src/daemon.ts"; }`.

  `bunNix` (optional)
  : Path to a `bun.nix` lockfile generated by `bun2nix`. Required when the
    project has npm dependencies. Omit for dependency-free projects.

  `bunBuildFlags` (optional)
  : Extra flags forwarded to `bun build`.

  `runtimeInputs` (optional)
  : Packages added to `PATH` in the wrapper script at runtime.

  `runtimeEnv` (optional)
  : Attrset of environment variables exported by the wrapper script.

  `bunfigPath` (optional)
  : Path to `bunfig.toml` for private registry credentials.

  `npmrcPath` (optional)
  : Path to `.npmrc` for private registry credentials.

  `overrides` (optional)
  : Attrset of `{ "pkg-name" = oldSrc: newSrc; }` source overrides forwarded
    to `fetchBunDeps`.

  `disableLint` (optional, default `false`)
  : Skip the eslint pass for this call. Useful when the lint stack flags
    a pattern that's intentional. Per-line escape hatches via
    `// eslint-disable-next-line n/no-process-exit` are preferred when
    only one site needs the exemption.

  # Type

  ```
  buildBunBinary  :: AttrSet -> Derivation
  buildBunBinaries :: AttrSet -> Derivation
  ```

  # Examples
  :::{.example}
  ## `buildBunBinary` usage example

  ```nix
  buildBunBinary {
    pname = "my-cli";
    version = "1.0.0";
    src = ./.;
    entrypoint = "src/cli.ts";
    bunNix = ./bun.nix;
  }
  ```

  :::
*/
{ pkgs, lib, bun, fetchBunDeps, eslintCache, mkWrapper, mkLint }:

let
  # Map a .ts/.tsx/.mts/.cts basename to .js
  tsToJs =
    name:
    lib.replaceStrings
      [
        ".ts"
        ".tsx"
        ".mts"
        ".cts"
      ]
      [
        ".js"
        ".js"
        ".js"
        ".js"
      ]
      (builtins.baseNameOf name);

  # Shared: create the bundle derivation for one or more entrypoints.
  # entrypointPaths is a list of source-relative paths. Lint, when
  # enabled, is its own derivation keyed only on
  # (src, eslintCache, entrypointPaths) and added as a buildInput so
  # failures propagate without re-running lint when unrelated bundle
  # inputs change. The lint derivation is attached to the bundle's
  # passthru so wrappers can re-expose it for testBuildFailure' targeting.
  mkBundle =
    {
      pname,
      version,
      src,
      entrypointPaths,
      bunNix ? null,
      bunBuildFlags ? [ ],
      bunfigPath ? null,
      npmrcPath ? null,
      overrides ? { },
      disableLint ? false,
    }:
    let
      hasDeps = bunNix != null;
      bunDeps = lib.optionalAttrs hasDeps {
        cache = fetchBunDeps {
          inherit bunNix bunfigPath npmrcPath overrides;
        };
      };
      runLint = !disableLint && eslintCache != null;
      lint = mkLint {
        inherit pname version src eslintCache entrypointPaths;
      };
    in
    pkgs.stdenvNoCC.mkDerivation {
      pname = "${pname}-bundle";
      inherit version src;

      nativeBuildInputs = [ bun ];
      buildInputs = lib.optional runLint lint;

      buildPhase = ''
        runHook preBuild

        ${lib.optionalString hasDeps ''
          export BUN_INSTALL_CACHE_DIR=$(mktemp -d)
          cp -r ${bunDeps.cache}/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"
          bun install --frozen-lockfile --linker=isolated
        ''}

        mkdir -p $out
        bun build ${lib.escapeShellArgs entrypointPaths} \
          --target=bun \
          --format=esm \
          --outdir=$out \
          ${lib.escapeShellArgs bunBuildFlags}

        runHook postBuild
      '';

      dontInstall = true;
      dontFixup = true;

      passthru = lib.optionalAttrs runLint { inherit lint; };
    };

in
{
  # Single entrypoint → single binary.
  buildBunBinary =
    {
      pname,
      version,
      src,
      entrypoint ? "index.ts",
      bunNix ? null,
      bunBuildFlags ? [ ],
      runtimeInputs ? [ ],
      runtimeEnv ? { },
      bunfigPath ? null,
      npmrcPath ? null,
      overrides ? { },
      disableLint ? false,
      ...
    }:
    let
      bundle = mkBundle {
        inherit
          pname
          version
          src
          bunNix
          bunBuildFlags
          bunfigPath
          npmrcPath
          overrides
          disableLint
          ;
        entrypointPaths = [ entrypoint ];
      };
    in
    mkWrapper {
      name = pname;
      inherit bundle runtimeInputs runtimeEnv;
      jsFile = tsToJs entrypoint;
      lint = bundle.passthru.lint or null;
    };

  # Multiple entrypoints → multiple binaries in one $out.
  # entrypoints is an attrset: { "bin-name" = "path/to/entry.ts"; ... }
  buildBunBinaries =
    {
      pname,
      version,
      src,
      entrypoints,
      bunNix ? null,
      bunBuildFlags ? [ ],
      runtimeInputs ? [ ],
      runtimeEnv ? { },
      bunfigPath ? null,
      npmrcPath ? null,
      overrides ? { },
      disableLint ? false,
      ...
    }:
    let
      bundle = mkBundle {
        inherit
          pname
          version
          src
          bunNix
          bunBuildFlags
          bunfigPath
          npmrcPath
          overrides
          disableLint
          ;
        entrypointPaths = builtins.attrValues entrypoints;
      };

      wrappers = lib.mapAttrsToList (
        name: entrypoint:
        mkWrapper {
          inherit name bundle runtimeInputs runtimeEnv;
          jsFile = tsToJs entrypoint;
          lint = bundle.passthru.lint or null;
        }
      ) entrypoints;
    in
    pkgs.symlinkJoin {
      name = pname;
      paths = wrappers;
    };
}
